### PR TITLE
Design/single-tablestyle

### PR DESCRIPTION
**Pull request by taisuou**
modified table style appearance

- A hide table contents between .markdown and overflow scroll

- B add monospace fonts to` <pre> `to beatuify white space 

A
スクリーンショット 2020-06-10 13 54

B 
スクリーンショット 2020-06-10 13 56

### CODE REVIEW

**Comment by kpango** [comment]
@taisuou could you please update the staging environment?
If you don't know about it, @vankichi will tell you how to deploy staging.

**Comment by vankichi** [comment]
I implemented some update on `refactor/template-and-sync-content` branch.
So, I'd like to merge this PR once and update staging environment.
Can I do that ? @kpango 

And, I'll share @taisuou how to deploy staging environment.

**Comment by kpango** [comment]
hmm, It's okay, I approve this PR.

**Comment by vankichi** [comment]
thx :)

**Pull request merged**
